version: "3"

services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

        #   frontend:
        #     build:
        #       context: ./frontend
        #       dockerfile: Dockerfile
        #     ports:
        #       - "3000:3000"
        #     environment:
        #       NODE_ENV: production

  backend:
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Change this if you want to, but keep it consisent: openssl rand -hex 32
      SECRET_KEY: 0feef9fb6d7360f1edd03ee62fd5042825851330948c94c15448f741e48aa046
    depends_on:
      - mongo

